name: Deploy Growtion App to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      working-directory: ./Frontend
      run: npm install

    - name: Build Vite project
      working-directory: ./Frontend
      run: npm run build

    - name: Deploy to /var/www/growtion
      run: |
        # Remove old files
        rm -rf /var/www/growtion/*
        # Copy new build
        cp -r ./Frontend/dist/* /var/www/growtion/
